<?php
/**
 * Client module for HiPanel
 *
 * @link      https://github.com/hiqdev/hipanel-module-client
 * @package   hipanel-module-client
 * @license   BSD-3-Clause
 * @copyright Copyright (c) 2015-2019, HiQDev (http://hiqdev.com/)
 */

namespace hipanel\modules\client\tests\unit\controllers;

use hipanel\modules\client\controllers\ClientController;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-22 at 14:39:12.
 */
class ClientControllerTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var ClientController
     */
    protected $object;

    protected function setUp(): void
    {
        $this->object = new ClientController('test', null);
    }

    protected function tearDown(): void
    {
    }

    public function testActions()
    {
        $this->assertInstanceOf(ClientController::class, $this->object);
    }
}
